version: '3.8'

services:
  # Servicio de Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "TiendaInazuma"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3307:3306" # Tu PC usar√° el 3307 para no chocar con XAMPP
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # Servicio de PHP (Ahora correctamente alineado)
  php:
    build: . 
    container_name: php_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public/:/var/www/html
      - ./src:/var/www/html
    depends_on:
      - db

volumes:
  db_data: